# Generated by Django 3.1 on 2024-08-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='idOrganizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.organizador', verbose_name='idOrganizador'),
        ),
    ]
