# Generated by Django 3.1 on 2024-08-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20240824_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='contacto',
            field=models.IntegerField(verbose_name='contacto'),
        ),
    ]
